### ISSUE TITLE
Buttons Error

### ISSUE THREAD

**Issue by xshadowbringer** [CasuallyCalm/discord-pretty-help#87]
TypeError: AppNav.next() takes 2 positional arguments but 3 were given

2023-04-30 16:23:49 ERROR    discord.ui.view Ignoring exception in view <AppNav timeout=10.0 children=4> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Next' emoji=None row=1>
Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ui\view.py", line 138, in __call__
    return self.callback(self.view, interaction, self.item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AppNav.next() takes 2 positional arguments but 3 were given

**Comment by CasuallyCalm** [comment]
Thank you for reporting, this has been fixed in v2.0.2.
